/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConfirmedRouteImport } from './routes/confirmed'
import { Route as IndexRouteImport } from './routes/index'

const ConfirmedRoute = ConfirmedRouteImport.update({
  id: '/confirmed',
  path: '/confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/confirmed': typeof ConfirmedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/confirmed': typeof ConfirmedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/confirmed': typeof ConfirmedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/confirmed'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/confirmed'
  id: '__root__' | '/' | '/confirmed'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfirmedRoute: typeof ConfirmedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/confirmed': {
      id: '/confirmed'
      path: '/confirmed'
      fullPath: '/confirmed'
      preLoaderRoute: typeof ConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfirmedRoute: ConfirmedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
